# Generated by Django 4.0.6 on 2022-07-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificator', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('sequence', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='organism_images/')),
            ],
        ),
    ]
