# Generated by Django 4.0.6 on 2022-07-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organism',
            fields=[
                ('identificator', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('string', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, upload_to='organism_images')),
            ],
        ),
    ]
